import { createRequestHandler } from "react-router";

declare module "react-router" {
  export interface AppLoadContext {
    cloudflare: {
      env: Cloudflare.Env;
      ctx: ExecutionContext;
    };
  }
}

const requestHandler = createRequestHandler(
  // This module is generated by `react-router build` before preview/deploy.
  // @ts-expect-error The server build only exists after the build step.
  () => import("../build/server/index.js"),
  "production",
);

export default {
  async fetch(request, env, ctx) {
    return requestHandler(request, {
      cloudflare: { env, ctx },
    });
  },
} satisfies ExportedHandler<Cloudflare.Env>;
